### ISSUE TITLE
Error on editing existing user

### ISSUE THREAD

**Issue by creisle** [bcgsc/pori_graphkb_schema#19]
**Describe the bug**

When trying to edit a user in the admin interface I see the following error

![2022-04-26_15-04](https://user-images.githubusercontent.com/4342641/165400366-db15019c-6be5-4dd6-8e02-eb2dcf02621d.png)

See attached console log 
[graphkbdev.bcgsc.ca-1651010819639.log](https://github.com/bcgsc/pori_graphkb_client/files/8567212/graphkbdev.bcgsc.ca-1651010819639.log)

**To Reproduce**

Pick an existing user, attempt to edit their details

**Comment by mathieulemieux** [comment]
When using the staging client server, I can edit an existing user by adding an email address, and I can change an existing email too. But I got an error when
![before](https://user-images.githubusercontent.com/4022327/166983359-9d49ed6c-ccb5-4543-852b-60a390aa2bdf.PNG)
 trying to save an existing user after deleting the email address though.
![After](https://user-images.githubusercontent.com/4022327/166983378-2ce46cfa-f29f-4b9e-bee4-adf485691d51.PNG)

![After](https://user-images.githubusercontent.com/4022327/166983412-27ab9243-e138-4baa-8466-5fab9297908b.PNG)
![error_on_delete](https://user-images.githubusercontent.com/4022327/166983454-4024365a-6fda-449f-931d-8a7003ac986e.PNG)

**Comment by creisle** [comment]
Ok so I wasn't able to reproduce this on the staging/prod deployments either. As far as I can tell they are both using schema 3.15.0 which was pre-typescript. In which case rather than doing this as a patch/bugfix let's make it a PR against the v4.0.0 release and include it there. It will mean we don't have to fix the merge conflicts later and we don't need to do a hotfix if this is not a production error anyway currently

**Comment by kttkjl** [comment]
Reopening, since it looks like the same problem still exists for the email field

On develop branch with node v16
![image](https://user-images.githubusercontent.com/25511396/203448089-8ca8540c-71fe-4501-9a09-750b4aa8aaeb.png)
